export enum CompanyContactRoleCode {
  OWNER = 'OWNER',
  CEO = 'CEO',
  FINANCE_DIRECTOR = 'FINANCE_DIRECTOR',
  ACCOUNTANT = 'ACCOUNTANT',
  TREASURER = 'TREASURER',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  AUTHORIZED_REPRESENTATIVE = 'AUTHORIZED_REPRESENTATIVE',
}
