export enum DealLossReasonCode {
  CLIENT_REFUSED = 'CLIENT_REFUSED',
  BANK_REJECTED = 'BANK_REJECTED',
  CONDITIONS_NOT_ACCEPTED = 'CONDITIONS_NOT_ACCEPTED',
  COMPETITOR = 'COMPETITOR',
  DUPLICATE = 'DUPLICATE',
  CANCELLED_BY_CLIENT = 'CANCELLED_BY_CLIENT',
  OTHER = 'OTHER',
}
