export enum DealSourceCode {
  WEBSITE = 'WEBSITE',
  BRANCH = 'BRANCH',
  CALL_CENTER = 'CALL_CENTER',
  MANAGER_OUTBOUND = 'MANAGER_OUTBOUND',
  PARTNER = 'PARTNER',
  REFERRAL = 'REFERRAL',
  REPEAT_CLIENT = 'REPEAT_CLIENT',
}
