export enum DealProductCode {
  CURRENT_ACCOUNT = 'CURRENT_ACCOUNT',
  LOAN = 'LOAN',
  DEPOSIT = 'DEPOSIT',
  SALARY_PROJECT = 'SALARY_PROJECT',
  ACQUIRING = 'ACQUIRING',
  BANK_GUARANTEE = 'BANK_GUARANTEE',
  LEASING = 'LEASING',
}
