export enum DealStageCode {
  LEAD = 'LEAD',
  QUALIFICATION = 'QUALIFICATION',
  OFFER_PREPARATION = 'OFFER_PREPARATION',
  CLIENT_APPROVAL = 'CLIENT_APPROVAL',
  BANK_REVIEW = 'BANK_REVIEW',
  DOCUMENT_SIGNING = 'DOCUMENT_SIGNING',
  WON = 'WON',
  LOST = 'LOST',
  CANCELLED = 'CANCELLED',
}
